
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8763/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mixluo/config-repo.git
          username: luoqiang92@126.com
          password: luoqiang0222
  rabbitmq:
    host: 192.168.40.128
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
